### ISSUE TITLE
Canonical key space is too small to cope with leaked information in the integer variant.

### ISSUE THREAD

**Issue by micklh** [erose1337/Destiny#3]
The technique demonstrated in `integerbased/secretkey.py` is not providing a few required guarantees of my analysis that we discussed previously (in private). I've even manually confirmed for this concrete example. The entire keyspace of secret encryption and decryption keys can be expressed as small polynomials. An efficient matrix technique can recover the secret encryption key from 8 known plaintexts. Another efficient matrix technique can recover the secret decryption key from the secret encryption key. This implies an attack that recovers the secret key from any public key that can produce ciphertexts with effective hamming weight > 7. This complements the Issue #2 attack which can decode any ciphertext with effective hamming weight < 11.

**Comment by erose1337** [comment]
I have no idea what you're talking about, unfortunately. If the key space is too small, that is an issue I understand and one that can be fixed easily. I did not intend for the paremeters in integerbased/secretkey.py to be the exact one used in a real world system, it's just something I drew up.

**Comment by erose1337** [comment]
("I have no idea what you're talking about" implies "I don't know how to fix that")

**Comment by micklh** [comment]
I believe you are getting ahead of yourself. Changing the size of the key space is not trivial, and even using all unique round keys over trillions of rounds will not change the situation. In fact, all my comments so far are 100% effective against a theoretically infinite number of rounds, using unique round keys every round. Simply put: All keys collide into a small group as the number of rounds goes to infinity, even using a truly random key schedule. I spent some time trying to search for a secure balance of the parameters but it's extremely difficult. I've found one configuration that appears to be out of the range of both the lattice and matrix attacks, but it produces 256MB ciphertexts for a 128-bit security level. (And no, there are not a lot of random masks used... Those seem to harm security more than they help at that scale.)

This GitHub issue format is not reasonable for further discussion as the topic is so intricate, and much experimentation is necessary to make any useful progress. A deep re-design is necessary and it's not something that can just be rolled into a quick comment. You know where to find me... it's doubtful that I'll check in on this project anymore, because the design concept that you refuse to re-consider absolutely can never be made secure and I have proven this multiple times and shared with you. "La-La-La! I'm not listening to (understanding) you!" does not protect confidential information in transit. I honestly hope you come to your senses before it's time to submit to NIST's call for post-quantum proposals :(

**Comment by erose1337** [comment]
I was listening to you and participating in the conversation, up until the last paragraph. I don't know why every time I participate in a conversation with you, you end up mocking and insulting me. Then, you wonder why I don't want to talk with you, regardless of what you have to say. I have been nothing but patient and objective, while you continue to insult me, sometimes for literally doing nothing. 

I don't even want to refute your points, because they are baseless accusations that literally do not even make sense. Just as an example, saying that I refuse to consider a re-design: you opened an issue and said it needed to be changed to operate over the integers, and I created a design which did so in a manner of days. How is that absolutely refusing? Personally, I think that's not only co-operating, but pretty damn impressive - Which leads me to my next point: 

How many people can you go to and demand a design for an algorithm that is partially homomorphic over the integers and have them produce it at all, ever, let alone in the time span I did for no compensation other then my own amusement? I think it is absolutely preposterous that you are insulting me. I simply do not want to consider conversation with you, regardless of the content. 

If you continue to mock me, insult me, or put words in my mouth ("La-La-La! I'm not listening to (understanding) you!" : where does this quotation come from? Please cite the time/place), I will seek appropriate measures to report abuse/harassment on whatever the platform in question is.

**Comment by erose1337** [comment]
Finally, addressing your statement: "I honestly hope you come to your senses before it's time to submit to NIST's call for post-quantum proposals"

I have not indicated anywhere that this project would be submitted to anything, ever. This sounds like a plan that you had/have. To be clear, I hope you do not consider yourself as some kind of co-author: I designed and implemented everything totally separate from you, before I even shared it with you. Your contribution would be cryptanalysis of the algorithm(s), not the design of them. 

Furthermore, what with your insistence of how "broken" the scheme is, I do not see why you think that would even be on the radar.

**Comment by micklh** [comment]
I don't at all consider myself a co-author of "Destiny", so yes let that be very clear. But, lets set aside silly games and just be human for a minute though... say whatever you want, I deeply understand the concepts I explained to you on Discord, and I am flattered that you are driven to explore possible implementations of it.

Nonetheless, putting broken in scare-quotes is not at all justified. The scheme is not just broken academically, and not just [practically](https://gist.github.com/micklh/ce1e501c76e8c2b61ad55e40ebd6d32a) (in polynomial time even), but algorithmicly. In order for the density of the subset sum problem to be hard, while the random padding is appropriate length for the public key, the block size must be less than half of one bit, which indicates that no computationally tractable configuration of this realization is secure.

**Comment by erose1337** [comment]
"The scheme" - the public key part, or the secret key part?

**Comment by micklh** [comment]
"The scheme" refers to the combined system. The secret key part is subject to known plaintext attack, and the public key part is rendered insecure because of that deficiency of the secret key part.

**Comment by erose1337** [comment]
I ask because the public key part is effectively equivalent to the scheme proposed in Fully Homomorphic Encryption Over The Integers, by Marten van Dijk, Craig Gentry, Shai Halevi, and Vinod Vaikuntanathan. So a total complete permanent break of the public key part would be significantly more surprising then a break of a 3 day old design by myself.

**Comment by micklh** [comment]
The authors in that publication have not made the same grave oversimplification of the design process that you have, and so my generalized attack does not apply to their encryption function. Again... they have incorporated the required number theory... as I mentioned.... such that particular critical operations yield hard problems. Whereas with this project, you've distorted my ideas (that I described in private, over a month ago, when you got starry-eyed and said you'll make a project called "Destiny"... I do keep and check logs of my Discord server.) based on being over-excited about understanding that tiny fraction of my design, relating to using homomorphic encryption to implement public key encryption. That part of my work is trivial, in a way I'm glad you couldn't understand the meat of what I said! because you tried to steal what I was kind enough to share! Do you not see how deeply you disrespect me by trying to say my teachings had nothing to do with this? After I spent so much of my time explaining number theory and information theory concepts to you, explaining how they relate to programming and optimization techniques... building up your self-confidence in general and telling you that you can do it and you can understand and just keep trying. You really think it's an appropriate thanks to try your hardest to say I was always useless to you? Really?

> a 3 day old design by myself.

Uh huh... The fact that [the attack I posted over 10 days ago](https://gist.github.com/micklh/ce1e501c76e8c2b61ad55e40ebd6d32a) works on this "variant" proves that it's nothing new, and sure as hell not something novel invented 3 days ago, otherwise it has a -7 day attack lol... You believe in causality right? *looks at Destiny timestamps from nearly a month ago* ;) Are you sure you're not bending reality too much here? Sorry, but I'm confident that you will not create anything secure because you failed to understand the most important part of my idea and how it relates to trapdoor functions. The conversations that excited you into creating this project were really just trivial results, you seemed to ignore the novel part I told you. Again, lucky for me since you're trying to steal it lol.
